version: '3.9'

services:
  api:
    build: .
    container_name: api_zeus
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - zeus_net

  db:
    image: mysql:8.0
    container_name: mysql_zeus
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base_zeus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zeus_net

volumes:
  mysql_data:

networks:
  zeus_net:
